export {default as Navbar } from './Navbar'
export {default as Hero} from './Hero'
export {default as Stats} from './Stats'
export {default as Business} from './Business'
export {default as Client} from './Client'
export {default as Testimonial} from './Testimonial'
export {default as CTA} from './CTA'
export {default as GetStarted} from './GetStarted'
export {default as FeedBackCard} from './FeedBackCard'
export {default as CardDeal} from './CardDeal'
export {default as Billing} from './Billing'
export {default as Button} from './Button'
export {default as Footer} from './Footer'
